In [1]:
# ================================
# FairXAI - Data Preprocessing
# Taiwan Credit Card Default
# ================================

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 120)

# Reproducibility
RANDOM_STATE = 42

print("Libraries imported successfully.")
print(f"Random state: {RANDOM_STATE}")

Libraries imported successfully.
Random state: 42

In [2]:
# Path to the FairXAI project
project_path = Path(r"D:\TY_Sem1\MLOps\FairXAi")

# Path to the original Taiwan dataset
dataset_path = project_path / "data" / "raw" / "taiwan_credit_default_original.xls"

print("Project exists:", project_path.exists())
print("Dataset exists:", dataset_path.exists())

if dataset_path.exists():
    print("Dataset path:", dataset_path)
    print("File size:", round(dataset_path.stat().st_size / (1024 * 1024), 2), "MB")

Project exists: True
Dataset exists: True
Dataset path: D:\TY_Sem1\MLOps\FairXAi\data\raw\taiwan_credit_default_original.xls
File size: 5.28 MB

In [3]:
# Load the original Taiwan Credit Card Default dataset

try:
    df = pd.read_excel(dataset_path, engine="xlrd")
    
    print("Dataset loaded successfully!")
    print("Shape:", df.shape)
    print("\nFirst 5 rows:")
    display(df.head())

except ImportError:
    print("xlrd is not installed.")
    print("Run: %pip install xlrd")

Dataset loaded successfully!
Shape: (30001, 25)

First 5 rows:

,Unnamed: 0,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
0,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,BILL_AMT2,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
1,1,20000,2,2,1,24,2,2,-1,-1,-2,-2,3913,3102,689,0,0,0,0,689,0,0,0,0,1
2,2,120000,2,2,2,26,-1,2,0,0,0,2,2682,1725,2682,3272,3455,3261,0,1000,1000,1000,0,2000,1
3,3,90000,2,2,2,34,0,0,0,0,0,0,29239,14027,13559,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
4,4,50000,2,2,1,37,0,0,0,0,0,0,46990,48233,49291,28314,28959,29547,2000,2019,1200,1100,1069,1000,0

In [4]:
# Inspect the raw structure of the loaded dataset

print("Shape:", df.shape)

print("\nColumn names:")
for i, col in enumerate(df.columns):
    print(i, repr(col))

print("\nFirst 3 rows as raw values:")
display(df.iloc[:3])

Shape: (30001, 25)

Column names:
0 'Unnamed: 0'
1 'X1'
2 'X2'
3 'X3'
4 'X4'
5 'X5'
6 'X6'
7 'X7'
8 'X8'
9 'X9'
10 'X10'
11 'X11'
12 'X12'
13 'X13'
14 'X14'
15 'X15'
16 'X16'
17 'X17'
18 'X18'
19 'X19'
20 'X20'
21 'X21'
22 'X22'
23 'X23'
24 'Y'

First 3 rows as raw values:

,Unnamed: 0,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,X11,X12,X13,X14,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
0,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,BILL_AMT2,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
1,1,20000,2,2,1,24,2,2,-1,-1,-2,-2,3913,3102,689,0,0,0,0,689,0,0,0,0,1
2,2,120000,2,2,2,26,-1,2,0,0,0,2,2682,1725,2682,3272,3455,3261,0,1000,1000,1000,0,2000,1

In [6]:
# Reload the dataset with the correct header row

df = pd.read_excel(
    dataset_path,
    engine="xlrd",
    header=1
)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Dataset loaded successfully!
Shape: (30000, 25)

Column names:
['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'default payment next month']

First 5 rows:

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,BILL_AMT2,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,-2,-2,3913,3102,689,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,0,2,2682,1725,2682,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,0,0,29239,14027,13559,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,0,0,46990,48233,49291,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,0,0,8617,5670,35835,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [7]:
# ==========================================
# Basic Dataset Information
# ==========================================

print("Dataset shape:", df.shape)

print("\nData types:")
print(df.dtypes)

print("\nDataset information:")
df.info()

Dataset shape: (30000, 25)

Data types:
ID                            int64
LIMIT_BAL                     int64
SEX                           int64
EDUCATION                     int64
MARRIAGE                      int64
AGE                           int64
PAY_0                         int64
PAY_2                         int64
PAY_3                         int64
PAY_4                         int64
PAY_5                         int64
PAY_6                         int64
BILL_AMT1                     int64
BILL_AMT2                     int64
BILL_AMT3                     int64
BILL_AMT4                     int64
BILL_AMT5                     int64
BILL_AMT6                     int64
PAY_AMT1                      int64
PAY_AMT2                      int64
PAY_AMT3                      int64
PAY_AMT4                      int64
PAY_AMT5                      int64
PAY_AMT6                      int64
default payment next month    int64
dtype: object

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  int64
 1   LIMIT_BAL                   30000 non-null  int64
 2   SEX                         30000 non-null  int64
 3   EDUCATION                   30000 non-null  int64
 4   MARRIAGE                    30000 non-null  int64
 5   AGE                         30000 non-null  int64
 6   PAY_0                       30000 non-null  int64
 7   PAY_2                       30000 non-null  int64
 8   PAY_3                       30000 non-null  int64
 9   PAY_4                       30000 non-null  int64
 10  PAY_5                       30000 non-null  int64
 11  PAY_6                       30000 non-null  int64
 12  BILL_AMT1                   30000 non-null  int64
 13  BILL_AMT2                   30000 non-null  int64
 14  BILL_AMT3                   30000 non-null  int64
 15  BILL_AMT4                   30000 non-null  int64
 16  BILL_AMT5                   30000 non-null  int64
 17  BILL_AMT6                   30000 non-null  int64
 18  PAY_AMT1                    30000 non-null  int64
 19  PAY_AMT2                    30000 non-null  int64
 20  PAY_AMT3                    30000 non-null  int64
 21  PAY_AMT4                    30000 non-null  int64
 22  PAY_AMT5                    30000 non-null  int64
 23  PAY_AMT6                    30000 non-null  int64
 24  default payment next month  30000 non-null  int64
dtypes: int64(25)
memory usage: 5.7 MB

In [8]:
# ==========================================
# Missing Values and Duplicate Records
# ==========================================

# Missing values
missing_values = df.isnull().sum()

print("Missing values by column:")
print(missing_values)

print("\nTotal missing values:", missing_values.sum())

# Duplicate rows
duplicate_count = df.duplicated().sum()

print("\nNumber of duplicate rows:", duplicate_count)

# Duplicate IDs
duplicate_ids = df["ID"].duplicated().sum()

print("Number of duplicate IDs:", duplicate_ids)

Missing values by column:
ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default payment next month    0
dtype: int64

Total missing values: 0

Number of duplicate rows: 0
Number of duplicate IDs: 0

In [9]:
# ==========================================
# Unique Values of Categorical / Ordinal Features
# ==========================================

categorical_columns = [
    "SEX",
    "EDUCATION",
    "MARRIAGE",
    "PAY_0",
    "PAY_2",
    "PAY_3",
    "PAY_4",
    "PAY_5",
    "PAY_6",
    "default payment next month"
]

for column in categorical_columns:
    print(f"\n{column}")
    print("-" * len(column))
    print(sorted(df[column].unique()))

SEX
---
[np.int64(1), np.int64(2)]

EDUCATION
---------
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6)]

MARRIAGE
--------
[np.int64(0), np.int64(1), np.int64(2), np.int64(3)]

PAY_0
-----
[np.int64(-2), np.int64(-1), np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)]

PAY_2
-----
[np.int64(-2), np.int64(-1), np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)]

PAY_3
-----
[np.int64(-2), np.int64(-1), np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)]

PAY_4
-----
[np.int64(-2), np.int64(-1), np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)]

PAY_5
-----
[np.int64(-2), np.int64(-1), np.int64(0), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)]

PAY_6
-----
[np.int64(-2), np.int64(-1), np.int64(0), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8)]

default payment next month
--------------------------
[np.int64(0), np.int64(1)]

In [10]:
# ==========================================
# Category Frequencies
# ==========================================

categorical_columns = [
    "SEX",
    "EDUCATION",
    "MARRIAGE",
    "PAY_0",
    "PAY_2",
    "PAY_3",
    "PAY_4",
    "PAY_5",
    "PAY_6"
]

for column in categorical_columns:
    print(f"\n{column}")
    print("-" * len(column))
    
    counts = df[column].value_counts().sort_index()
    percentages = (df[column].value_counts(normalize=True).sort_index() * 100).round(2)
    
    result = pd.DataFrame({
        "Count": counts,
        "Percentage": percentages
    })
    
    display(result)

SEX
---

     Count  Percentage
SEX
1    11888       39.63
2    18112       60.37

EDUCATION
---------

           Count  Percentage
EDUCATION
0             14        0.05
1          10585       35.28
2          14030       46.77
3           4917       16.39
4            123        0.41
5            280        0.93
6             51        0.17

MARRIAGE
--------

          Count  Percentage
MARRIAGE
0            54        0.18
1         13659       45.53
2         15964       53.21
3           323        1.08

PAY_0
-----

       Count  Percentage
PAY_0
-2      2759        9.20
-1      5686       18.95
 0     14737       49.12
 1      3688       12.29
 2      2667        8.89
 3       322        1.07
 4        76        0.25
 5        26        0.09
 6        11        0.04
 7         9        0.03
 8        19        0.06

PAY_2
-----

       Count  Percentage
PAY_2
-2      3782       12.61
-1      6050       20.17
 0     15730       52.43
 1        28        0.09
 2      3927       13.09
 3       326        1.09
 4        99        0.33
 5        25        0.08
 6        12        0.04
 7        20        0.07
 8         1        0.00

PAY_3
-----

       Count  Percentage
PAY_3
-2      4085       13.62
-1      5938       19.79
 0     15764       52.55
 1         4        0.01
 2      3819       12.73
 3       240        0.80
 4        76        0.25
 5        21        0.07
 6        23        0.08
 7        27        0.09
 8         3        0.01

PAY_4
-----

       Count  Percentage
PAY_4
-2      4348       14.49
-1      5687       18.96
 0     16455       54.85
 1         2        0.01
 2      3159       10.53
 3       180        0.60
 4        69        0.23
 5        35        0.12
 6         5        0.02
 7        58        0.19
 8         2        0.01

PAY_5
-----

       Count  Percentage
PAY_5
-2      4546       15.15
-1      5539       18.46
 0     16947       56.49
 2      2626        8.75
 3       178        0.59
 4        84        0.28
 5        17        0.06
 6         4        0.01
 7        58        0.19
 8         1        0.00

PAY_6
-----

       Count  Percentage
PAY_6
-2      4895       16.32
-1      5740       19.13
 0     16286       54.29
 2      2766        9.22
 3       184        0.61
 4        49        0.16
 5        13        0.04
 6        19        0.06
 7        46        0.15
 8         2        0.01

In [11]:
# ==========================================
# Numerical Feature Range Check
# ==========================================

numerical_columns = [
    "LIMIT_BAL",
    "AGE",
    "BILL_AMT1", "BILL_AMT2", "BILL_AMT3",
    "BILL_AMT4", "BILL_AMT5", "BILL_AMT6",
    "PAY_AMT1", "PAY_AMT2", "PAY_AMT3",
    "PAY_AMT4", "PAY_AMT5", "PAY_AMT6"
]

range_summary = pd.DataFrame({
    "Min": df[numerical_columns].min(),
    "Max": df[numerical_columns].max(),
    "Mean": df[numerical_columns].mean().round(2),
    "Median": df[numerical_columns].median()
})

display(range_summary)

              Min      Max       Mean    Median
LIMIT_BAL   10000  1000000  167484.32  140000.0
AGE            21       79      35.49      34.0
BILL_AMT1 -165580   964511   51223.33   22381.5
BILL_AMT2  -69777   983931   49179.08   21200.0
BILL_AMT3 -157264  1664089   47013.15   20088.5
BILL_AMT4 -170000   891586   43262.95   19052.0
BILL_AMT5  -81334   927171   40311.40   18104.5
BILL_AMT6 -339603   961664   38871.76   17071.0
PAY_AMT1        0   873552    5663.58    2100.0
PAY_AMT2        0  1684259    5921.16    2009.0
PAY_AMT3        0   896040    5225.68    1800.0
PAY_AMT4        0   621000    4826.08    1500.0
PAY_AMT5        0   426529    4799.39    1500.0
PAY_AMT6        0   528666    5215.50    1500.0

In [12]:
# ==========================================
# Target Distribution
# ==========================================

target_column = "default payment next month"

target_counts = df[target_column].value_counts().sort_index()
target_percentages = (
    df[target_column]
    .value_counts(normalize=True)
    .sort_index() * 100
).round(2)

target_summary = pd.DataFrame({
    "Count": target_counts,
    "Percentage": target_percentages
})

print("Target distribution:")
display(target_summary)

print(f"Total observations: {len(df):,}")
print(f"Default cases (1): {target_counts[1]:,} ({target_percentages[1]}%)")
print(f"Non-default cases (0): {target_counts[0]:,} ({target_percentages[0]}%)")

Target distribution:

                            Count  Percentage
default payment next month
0                           23364       77.88
1                            6636       22.12

Total observations: 30,000
Default cases (1): 6,636 (22.12%)
Non-default cases (0): 23,364 (77.88%)

In [13]:
# ==========================================
# Statistical Summary
# ==========================================

summary = df.describe().T

summary["missing"] = df.isnull().sum()
summary["unique"] = df.nunique()

display(summary)

,count,mean,std,min,25%,50%,75%,max,missing,unique
ID,30000.0,15000.500000,8660.398374,1.0,7500.75,15000.5,22500.25,30000.0,0,30000
LIMIT_BAL,30000.0,167484.322667,129747.661567,10000.0,50000.00,140000.0,240000.00,1000000.0,0,81
SEX,30000.0,1.603733,0.489129,1.0,1.00,2.0,2.00,2.0,0,2
EDUCATION,30000.0,1.853133,0.790349,0.0,1.00,2.0,2.00,6.0,0,7
MARRIAGE,30000.0,1.551867,0.521970,0.0,1.00,2.0,2.00,3.0,0,4
AGE,30000.0,35.485500,9.217904,21.0,28.00,34.0,41.00,79.0,0,56
PAY_0,30000.0,-0.016700,1.123802,-2.0,-1.00,0.0,0.00,8.0,0,11
PAY_2,30000.0,-0.133767,1.197186,-2.0,-1.00,0.0,0.00,8.0,0,11
PAY_3,30000.0,-0.166200,1.196868,-2.0,-1.00,0.0,0.00,8.0,0,11
PAY_4,30000.0,-0.220667,1.169139,-2.0,-1.00,0.0,0.00,8.0,0,11
PAY_5,30000.0,-0.266200,1.133187,-2.0,-1.00,0.0,0.00,8.0,0,10
PAY_6,30000.0,-0.291100,1.149988,-2.0,-1.00,0.0,0.00,8.0,0,10
BILL_AMT1,30000.0,51223.330900,73635.860576,-165580.0,3558.75,22381.5,67091.00,964511.0,0,22723
BILL_AMT2,30000.0,49179.075167,71173.768783,-69777.0,2984.75,21200.0,64006.25,983931.0,0,22346
BILL_AMT3,30000.0,47013.154800,69349.387427,-157264.0,2666.25,20088.5,60164.75,1664089.0,0,22026
BILL_AMT4,30000.0,43262.948967,64332.856134,-170000.0,2326.75,19052.0,54506.00,891586.0,0,21548
BILL_AMT5,30000.0,40311.400967,60797.155770,-81334.0,1763.00,18104.5,50190.50,927171.0,0,21010
BILL_AMT6,30000.0,38871.760400,59554.107537,-339603.0,1256.00,17071.0,49198.25,961664.0,0,20604
PAY_AMT1,30000.0,5663.580500,16563.280354,0.0,1000.00,2100.0,5006.00,873552.0,0,7943
PAY_AMT2,30000.0,5921.163500,23040.870402,0.0,833.00,2009.0,5000.00,1684259.0,0,7899
PAY_AMT3,30000.0,5225.681500,17606.961470,0.0,390.00,1800.0,4505.00,896040.0,0,7518
PAY_AMT4,30000.0,4826.076867,15666.159744,0.0,296.00,1500.0,4013.25,621000.0,0,6937
PAY_AMT5,30000.0,4799.387633,15278.305679,0.0,252.50,1500.0,4031.50,426529.0,0,6897
PAY_AMT6,30000.0,5215.502567,17777.465775,0.0,117.75,1500.0,4000.00,528666.0,0,6939
default payment next month,30000.0,0.221200,0.415062,0.0,0.00,0.0,0.00,1.0,0,2

In [14]:
# ==========================================
# Feature Groups for Preprocessing
# ==========================================

target_column = "default payment next month"

# Identifier — not used as a model feature
id_column = "ID"

# Categorical demographic features
categorical_columns = [
    "SEX",
    "EDUCATION",
    "MARRIAGE"
]

# Ordinal repayment-status features
ordinal_columns = [
    "PAY_0",
    "PAY_2",
    "PAY_3",
    "PAY_4",
    "PAY_5",
    "PAY_6"
]

# Continuous numerical features
numerical_columns = [
    "LIMIT_BAL",
    "AGE",
    "BILL_AMT1",
    "BILL_AMT2",
    "BILL_AMT3",
    "BILL_AMT4",
    "BILL_AMT5",
    "BILL_AMT6",
    "PAY_AMT1",
    "PAY_AMT2",
    "PAY_AMT3",
    "PAY_AMT4",
    "PAY_AMT5",
    "PAY_AMT6"
]

# All model features
feature_columns = categorical_columns + ordinal_columns + numerical_columns

print("Feature groups defined successfully.\n")

print("ID column:")
print(id_column)

print("\nCategorical columns:")
print(categorical_columns)

print("\nOrdinal columns:")
print(ordinal_columns)

print("\nNumerical columns:")
print(numerical_columns)

print("\nTotal model features:", len(feature_columns))
print("Target column:", target_column)

Feature groups defined successfully.

ID column:
ID

Categorical columns:
['SEX', 'EDUCATION', 'MARRIAGE']

Ordinal columns:
['PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6']

Numerical columns:
['LIMIT_BAL', 'AGE', 'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6']

Total model features: 23
Target column: default payment next month

In [15]:
# ==========================================
# Separate Features and Target
# ==========================================

# Features
X = df[feature_columns].copy()

# Target
y = df[target_column].copy()

print("Features (X):")
print("Shape:", X.shape)

print("\nTarget (y):")
print("Shape:", y.shape)

print("\nTarget values:")
print(y.value_counts().sort_index())

print("\nFirst 5 rows of X:")
display(X.head())

print("\nFirst 5 values of y:")
display(y.head())

Features (X):
Shape: (30000, 23)

Target (y):
Shape: (30000,)

Target values:
default payment next month
0    23364
1     6636
Name: count, dtype: int64

First 5 rows of X:

,SEX,EDUCATION,MARRIAGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,LIMIT_BAL,AGE,BILL_AMT1,BILL_AMT2,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,2,2,1,2,2,-1,-1,-2,-2,20000,24,3913,3102,689,0,0,0,0,689,0,0,0,0
1,2,2,2,-1,2,0,0,0,2,120000,26,2682,1725,2682,3272,3455,3261,0,1000,1000,1000,0,2000
2,2,2,2,0,0,0,0,0,0,90000,34,29239,14027,13559,14331,14948,15549,1518,1500,1000,1000,1000,5000
3,2,2,1,0,0,0,0,0,0,50000,37,46990,48233,49291,28314,28959,29547,2000,2019,1200,1100,1069,1000
4,1,2,1,-1,0,-1,0,0,0,50000,57,8617,5670,35835,20940,19146,19131,2000,36681,10000,9000,689,679

First 5 values of y:

0    1
1    1
2    0
3    0
4    0
Name: default payment next month, dtype: int64

In [16]:
# ==========================================
# Categorical Feature Categories
# ==========================================

for column in categorical_columns:
    print(f"\n{column}")
    print("Categories:", sorted(X[column].unique()))
    print("Number of categories:", X[column].nunique())

SEX
Categories: [np.int64(1), np.int64(2)]
Number of categories: 2

EDUCATION
Categories: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6)]
Number of categories: 7

MARRIAGE
Categories: [np.int64(0), np.int64(1), np.int64(2), np.int64(3)]
Number of categories: 4

In [17]:
# ==========================================
# Preprocessing Pipeline
# ==========================================

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline

# Categorical preprocessing
categorical_transformer = Pipeline(
    steps=[
        ("onehot", OneHotEncoder(
            handle_unknown="ignore",
            sparse_output=False
        ))
    ]
)

# Numerical + ordinal preprocessing
numerical_ordinal_columns = ordinal_columns + numerical_columns

numerical_ordinal_transformer = Pipeline(
    steps=[
        ("scaler", StandardScaler())
    ]
)

# Combine both transformations
preprocessor = ColumnTransformer(
    transformers=[
        ("categorical", categorical_transformer, categorical_columns),
        ("numerical_ordinal", numerical_ordinal_transformer, numerical_ordinal_columns)
    ],
    remainder="drop"
)

print("Preprocessing pipeline created successfully.")
print("\nCategorical columns:", categorical_columns)
print("Ordinal + numerical columns:", len(numerical_ordinal_columns))
print("Total input features:", len(feature_columns))

Preprocessing pipeline created successfully.

Categorical columns: ['SEX', 'EDUCATION', 'MARRIAGE']
Ordinal + numerical columns: 20
Total input features: 23

In [18]:
# ==========================================
# Corrected Preprocessing Pipeline
# ==========================================

# Continuous numerical features that need scaling
continuous_columns = [
    "LIMIT_BAL",
    "AGE",
    "BILL_AMT1",
    "BILL_AMT2",
    "BILL_AMT3",
    "BILL_AMT4",
    "BILL_AMT5",
    "BILL_AMT6",
    "PAY_AMT1",
    "PAY_AMT2",
    "PAY_AMT3",
    "PAY_AMT4",
    "PAY_AMT5",
    "PAY_AMT6"
]

# Ordinal repayment-status features
ordinal_columns = [
    "PAY_0",
    "PAY_2",
    "PAY_3",
    "PAY_4",
    "PAY_5",
    "PAY_6"
]

# Categorical demographic features
categorical_columns = [
    "SEX",
    "EDUCATION",
    "MARRIAGE"
]

# Preprocessing for categorical features
categorical_transformer = Pipeline(
    steps=[
        ("onehot", OneHotEncoder(
            handle_unknown="ignore",
            sparse_output=False
        ))
    ]
)

# Preprocessing for continuous numerical features
continuous_transformer = Pipeline(
    steps=[
        ("scaler", StandardScaler())
    ]
)

# Combine transformations
preprocessor = ColumnTransformer(
    transformers=[
        ("categorical", categorical_transformer, categorical_columns),
        ("continuous", continuous_transformer, continuous_columns)
    ],
    remainder="passthrough"
)

print("Corrected preprocessing pipeline created successfully.")

print("\nCategorical columns:", len(categorical_columns))
print("Ordinal columns:", len(ordinal_columns))
print("Continuous numerical columns:", len(continuous_columns))
print("Total input features:", len(feature_columns))

Corrected preprocessing pipeline created successfully.

Categorical columns: 3
Ordinal columns: 6
Continuous numerical columns: 14
Total input features: 23

In [19]:
# ==========================================
# Repayment Status Code Distribution
# ==========================================

for column in ordinal_columns:
    print(f"\n{column}")
    print("-" * len(column))
    
    counts = X[column].value_counts().sort_index()
    
    display(
        pd.DataFrame({
            "Count": counts,
            "Percentage": (counts / len(X) * 100).round(2)
        })
    )

PAY_0
-----

       Count  Percentage
PAY_0
-2      2759        9.20
-1      5686       18.95
 0     14737       49.12
 1      3688       12.29
 2      2667        8.89
 3       322        1.07
 4        76        0.25
 5        26        0.09
 6        11        0.04
 7         9        0.03
 8        19        0.06

PAY_2
-----

       Count  Percentage
PAY_2
-2      3782       12.61
-1      6050       20.17
 0     15730       52.43
 1        28        0.09
 2      3927       13.09
 3       326        1.09
 4        99        0.33
 5        25        0.08
 6        12        0.04
 7        20        0.07
 8         1        0.00

PAY_3
-----

       Count  Percentage
PAY_3
-2      4085       13.62
-1      5938       19.79
 0     15764       52.55
 1         4        0.01
 2      3819       12.73
 3       240        0.80
 4        76        0.25
 5        21        0.07
 6        23        0.08
 7        27        0.09
 8         3        0.01

PAY_4
-----

       Count  Percentage
PAY_4
-2      4348       14.49
-1      5687       18.96
 0     16455       54.85
 1         2        0.01
 2      3159       10.53
 3       180        0.60
 4        69        0.23
 5        35        0.12
 6         5        0.02
 7        58        0.19
 8         2        0.01

PAY_5
-----

       Count  Percentage
PAY_5
-2      4546       15.15
-1      5539       18.46
 0     16947       56.49
 2      2626        8.75
 3       178        0.59
 4        84        0.28
 5        17        0.06
 6         4        0.01
 7        58        0.19
 8         1        0.00

PAY_6
-----

       Count  Percentage
PAY_6
-2      4895       16.32
-1      5740       19.13
 0     16286       54.29
 2      2766        9.22
 3       184        0.61
 4        49        0.16
 5        13        0.04
 6        19        0.06
 7        46        0.15
 8         2        0.01

In [20]:
# ==========================================
# Train-Test Split
# ==========================================

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=RANDOM_STATE,
    stratify=y
)

print("Train-Test split completed.\n")

print("Training data:")
print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("\nTesting data:")
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

print("\nTarget distribution:")

print("\nTraining set:")
print(y_train.value_counts())
print((y_train.value_counts(normalize=True) * 100).round(2))

print("\nTesting set:")
print(y_test.value_counts())
print((y_test.value_counts(normalize=True) * 100).round(2))

Train-Test split completed.

Training data:
X_train: (24000, 23)
y_train: (24000,)

Testing data:
X_test: (6000, 23)
y_test: (6000,)

Target distribution:

Training set:
default payment next month
0    18691
1     5309
Name: count, dtype: int64
default payment next month
0    77.88
1    22.12
Name: proportion, dtype: float64

Testing set:
default payment next month
0    4673
1    1327
Name: count, dtype: int64
default payment next month
0    77.88
1    22.12
Name: proportion, dtype: float64

In [21]:
# ==========================================
# Save Train-Test Split
# ==========================================

# Create the split directory
split_path = project_path / "data" / "split"
split_path.mkdir(parents=True, exist_ok=True)

# Combine features and target for easier versioning and reproducibility
train_data = X_train.copy()
train_data[target_column] = y_train

test_data = X_test.copy()
test_data[target_column] = y_test

# Save the split datasets
train_data.to_csv(split_path / "train.csv", index=False)
test_data.to_csv(split_path / "test.csv", index=False)

print("Train-test split saved successfully!\n")

print("Saved files:")
for file in sorted(split_path.iterdir()):
    print(f"- {file.name} ({file.stat().st_size / 1024:.2f} KB)")

print("\nTraining file shape:", train_data.shape)
print("Testing file shape:", test_data.shape)

print("\nSplit directory:")
print(split_path)

Train-test split saved successfully!

Saved files:
- test.csv (533.27 KB)
- train.csv (2131.30 KB)

Training file shape: (24000, 24)
Testing file shape: (6000, 24)

Split directory:
D:\TY_Sem1\MLOps\FairXAi\data\split

In [22]:
# ==========================================
# Verify Saved Split
# ==========================================

# Load the versioned split files back from disk
train_check = pd.read_csv(split_path / "train.csv")
test_check = pd.read_csv(split_path / "test.csv")

print("Saved split verification:\n")

print("Train shape:", train_check.shape)
print("Test shape :", test_check.shape)

# Verify that the saved files match the in-memory datasets
train_match = train_data.reset_index(drop=True).equals(
    train_check.reset_index(drop=True)
)

test_match = test_data.reset_index(drop=True).equals(
    test_check.reset_index(drop=True)
)

print("\nTrain data matches in-memory split:", train_match)
print("Test data matches in-memory split :", test_match)

# Verify target distributions once more
print("\nTrain target distribution:")
print(train_check[target_column].value_counts())

print("\nTest target distribution:")
print(test_check[target_column].value_counts())

Saved split verification:

Train shape: (24000, 24)
Test shape : (6000, 24)

Train data matches in-memory split: True
Test data matches in-memory split : True

Train target distribution:
default payment next month
0    18691
1     5309
Name: count, dtype: int64

Test target distribution:
default payment next month
0    4673
1    1327
Name: count, dtype: int64

In [23]:
# ==========================================
# Fit Preprocessor on Training Data
# ==========================================

# Fit the preprocessor ONLY on training data
# and transform the training features
X_train_processed = preprocessor.fit_transform(X_train)

# Use the SAME fitted preprocessor to transform test features
X_test_processed = preprocessor.transform(X_test)

print("Preprocessing completed successfully!\n")

print("Original training shape :", X_train.shape)
print("Processed training shape:", X_train_processed.shape)

print("\nOriginal testing shape  :", X_test.shape)
print("Processed testing shape :", X_test_processed.shape)

print("\nProcessed data type:", type(X_train_processed))

Preprocessing completed successfully!

Original training shape : (24000, 23)
Processed training shape: (24000, 33)

Original testing shape  : (6000, 23)
Processed testing shape : (6000, 33)

Processed data type: <class 'numpy.ndarray'>

In [24]:
# ==========================================
# Validate Processed Data
# ==========================================

# Check for missing and infinite values
train_nan = np.isnan(X_train_processed).sum()
test_nan = np.isnan(X_test_processed).sum()

train_inf = np.isinf(X_train_processed).sum()
test_inf = np.isinf(X_test_processed).sum()

print("Missing values:")
print("X_train_processed:", train_nan)
print("X_test_processed :", test_nan)

print("\nInfinite values:")
print("X_train_processed:", train_inf)
print("X_test_processed :", test_inf)

# Convert processed arrays to DataFrames temporarily
# using the feature names generated by the preprocessor
processed_feature_names = preprocessor.get_feature_names_out()

X_train_processed_df = pd.DataFrame(
    X_train_processed,
    columns=processed_feature_names,
    index=X_train.index
)

X_test_processed_df = pd.DataFrame(
    X_test_processed,
    columns=processed_feature_names,
    index=X_test.index
)

print("\nProcessed feature count:", len(processed_feature_names))

print("\nFirst 15 processed feature names:")
print(processed_feature_names[:15])

print("\nLast 10 processed feature names:")
print(processed_feature_names[-10:])

print("\nProcessed training data preview:")
display(X_train_processed_df.head())

Missing values:
X_train_processed: 0
X_test_processed : 0

Infinite values:
X_train_processed: 0
X_test_processed : 0

Processed feature count: 33

First 15 processed feature names:
['categorical__SEX_1' 'categorical__SEX_2' 'categorical__EDUCATION_0'
 'categorical__EDUCATION_1' 'categorical__EDUCATION_2'
 'categorical__EDUCATION_3' 'categorical__EDUCATION_4'
 'categorical__EDUCATION_5' 'categorical__EDUCATION_6'
 'categorical__MARRIAGE_0' 'categorical__MARRIAGE_1'
 'categorical__MARRIAGE_2' 'categorical__MARRIAGE_3'
 'continuous__LIMIT_BAL' 'continuous__AGE']

Last 10 processed feature names:
['continuous__PAY_AMT3' 'continuous__PAY_AMT4' 'continuous__PAY_AMT5'
 'continuous__PAY_AMT6' 'remainder__PAY_0' 'remainder__PAY_2'
 'remainder__PAY_3' 'remainder__PAY_4' 'remainder__PAY_5'
 'remainder__PAY_6']

Processed training data preview:

,categorical__SEX_1,categorical__SEX_2,categorical__EDUCATION_0,categorical__EDUCATION_1,categorical__EDUCATION_2,categorical__EDUCATION_3,categorical__EDUCATION_4,categorical__EDUCATION_5,categorical__EDUCATION_6,categorical__MARRIAGE_0,categorical__MARRIAGE_1,categorical__MARRIAGE_2,categorical__MARRIAGE_3,continuous__LIMIT_BAL,continuous__AGE,continuous__BILL_AMT1,continuous__BILL_AMT2,continuous__BILL_AMT3,continuous__BILL_AMT4,continuous__BILL_AMT5,continuous__BILL_AMT6,continuous__PAY_AMT1,continuous__PAY_AMT2,continuous__PAY_AMT3,continuous__PAY_AMT4,continuous__PAY_AMT5,continuous__PAY_AMT6,remainder__PAY_0,remainder__PAY_2,remainder__PAY_3,remainder__PAY_4,remainder__PAY_5,remainder__PAY_6
22788,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-0.056866,-0.264558,1.505547,1.745089,1.778869,1.891679,2.020839,2.096346,0.580657,-0.290332,-0.297820,0.086961,0.500397,0.048745,2.0,2.0,3.0,2.0,0.0,0.0
29006,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-0.134081,-0.155804,-0.695165,-0.691138,-0.685090,-0.673845,-0.662488,-0.652126,-0.344969,-0.290332,-0.297820,-0.318075,-0.316978,-0.292992,1.0,-1.0,-1.0,-2.0,-2.0,-2.0
16950,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-1.215090,1.584260,-0.556800,-0.576836,-0.561615,-0.547887,-0.526789,-0.510492,-0.348128,-0.227081,-0.233069,-0.298554,-0.296710,-0.236970,1.0,2.0,0.0,0.0,0.0,0.0
22280,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.406423,-0.699574,2.119190,2.287237,2.460102,2.738001,1.509166,1.613118,0.215287,0.154056,0.152526,0.000642,0.008643,0.043143,0.0,0.0,0.0,0.0,0.0,0.0
11346,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.101358,-0.373312,-0.695165,-0.691886,-0.680324,-0.668755,-0.666365,-0.656089,-0.348251,-0.274236,-0.297820,-0.318075,-0.316978,-0.225765,1.0,-2.0,-1.0,0.0,0.0,-2.0

In [25]:
# ==========================================
# Create Final Processed Datasets
# ==========================================

# Create clean DataFrames from the processed arrays
X_train_processed_df = pd.DataFrame(
    X_train_processed,
    columns=processed_feature_names
)

X_test_processed_df = pd.DataFrame(
    X_test_processed,
    columns=processed_feature_names
)

# Add the target column back to each dataset
train_processed = X_train_processed_df.copy()
train_processed[target_column] = y_train.reset_index(drop=True)

test_processed = X_test_processed_df.copy()
test_processed[target_column] = y_test.reset_index(drop=True)

print("Final processed datasets created successfully!\n")

print("Processed training shape:", train_processed.shape)
print("Processed testing shape :", test_processed.shape)

print("\nNumber of feature columns:", len(processed_feature_names))
print("Target column:", target_column)

print("\nFirst 5 rows of processed training data:")
display(train_processed.head())

print("\nTarget distribution:")
print("\nTraining:")
print(train_processed[target_column].value_counts())

print("\nTesting:")
print(test_processed[target_column].value_counts())

Final processed datasets created successfully!

Processed training shape: (24000, 34)
Processed testing shape : (6000, 34)

Number of feature columns: 33
Target column: default payment next month

First 5 rows of processed training data:

,categorical__SEX_1,categorical__SEX_2,categorical__EDUCATION_0,categorical__EDUCATION_1,categorical__EDUCATION_2,categorical__EDUCATION_3,categorical__EDUCATION_4,categorical__EDUCATION_5,categorical__EDUCATION_6,categorical__MARRIAGE_0,categorical__MARRIAGE_1,categorical__MARRIAGE_2,categorical__MARRIAGE_3,continuous__LIMIT_BAL,continuous__AGE,continuous__BILL_AMT1,continuous__BILL_AMT2,continuous__BILL_AMT3,continuous__BILL_AMT4,continuous__BILL_AMT5,continuous__BILL_AMT6,continuous__PAY_AMT1,continuous__PAY_AMT2,continuous__PAY_AMT3,continuous__PAY_AMT4,continuous__PAY_AMT5,continuous__PAY_AMT6,remainder__PAY_0,remainder__PAY_2,remainder__PAY_3,remainder__PAY_4,remainder__PAY_5,remainder__PAY_6,default payment next month
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-0.056866,-0.264558,1.505547,1.745089,1.778869,1.891679,2.020839,2.096346,0.580657,-0.290332,-0.297820,0.086961,0.500397,0.048745,2.0,2.0,3.0,2.0,0.0,0.0,0
1,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-0.134081,-0.155804,-0.695165,-0.691138,-0.685090,-0.673845,-0.662488,-0.652126,-0.344969,-0.290332,-0.297820,-0.318075,-0.316978,-0.292992,1.0,-1.0,-1.0,-2.0,-2.0,-2.0,0
2,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-1.215090,1.584260,-0.556800,-0.576836,-0.561615,-0.547887,-0.526789,-0.510492,-0.348128,-0.227081,-0.233069,-0.298554,-0.296710,-0.236970,1.0,2.0,0.0,0.0,0.0,0.0,0
3,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.406423,-0.699574,2.119190,2.287237,2.460102,2.738001,1.509166,1.613118,0.215287,0.154056,0.152526,0.000642,0.008643,0.043143,0.0,0.0,0.0,0.0,0.0,0.0,1
4,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.101358,-0.373312,-0.695165,-0.691886,-0.680324,-0.668755,-0.666365,-0.656089,-0.348251,-0.274236,-0.297820,-0.318075,-0.316978,-0.225765,1.0,-2.0,-1.0,0.0,0.0,-2.0,0

Target distribution:

Training:
default payment next month
0    18691
1     5309
Name: count, dtype: int64

Testing:
default payment next month
0    4673
1    1327
Name: count, dtype: int64

In [26]:
# ==========================================
# Save Processed Train-Test Data
# ==========================================

# Create the processed data directory
processed_path = project_path / "data" / "processed"
processed_path.mkdir(parents=True, exist_ok=True)

# Save processed training and testing datasets
train_processed.to_csv(
    processed_path / "train_processed.csv",
    index=False
)

test_processed.to_csv(
    processed_path / "test_processed.csv",
    index=False
)

print("Processed datasets saved successfully!\n")

print("Saved files:")
for file in sorted(processed_path.iterdir()):
    print(f"- {file.name} ({file.stat().st_size / (1024 * 1024):.2f} MB)")

print("\nTraining processed shape:", train_processed.shape)
print("Testing processed shape :", test_processed.shape)

print("\nProcessed data directory:")
print(processed_path)

Processed datasets saved successfully!

Saved files:
- test_processed.csv (2.07 MB)
- train_processed.csv (8.28 MB)

Training processed shape: (24000, 34)
Testing processed shape : (6000, 34)

Processed data directory:
D:\TY_Sem1\MLOps\FairXAi\data\processed

In [27]:
# ==========================================
# Verify Saved Processed Data
# ==========================================

# Load the processed datasets back from disk
train_processed_check = pd.read_csv(
    processed_path / "train_processed.csv"
)

test_processed_check = pd.read_csv(
    processed_path / "test_processed.csv"
)

print("Processed data verification:\n")

print("Train shape:", train_processed_check.shape)
print("Test shape :", test_processed_check.shape)

# Verify exact equality with the processed DataFrames
train_processed_match = train_processed.equals(
    train_processed_check
)

test_processed_match = test_processed.equals(
    test_processed_check
)

print("\nTrain processed data matches saved file:", train_processed_match)
print("Test processed data matches saved file :", test_processed_match)

# Check for missing and infinite values after saving/loading
train_missing = train_processed_check.isna().sum().sum()
test_missing = test_processed_check.isna().sum().sum()

train_infinite = np.isinf(
    train_processed_check.select_dtypes(include=np.number)
).sum().sum()

test_infinite = np.isinf(
    test_processed_check.select_dtypes(include=np.number)
).sum().sum()

print("\nMissing values:")
print("Train:", train_missing)
print("Test :", test_missing)

print("\nInfinite values:")
print("Train:", train_infinite)
print("Test :", test_infinite)

print("\nVerification completed.")

Processed data verification:

Train shape: (24000, 34)
Test shape : (6000, 34)

Train processed data matches saved file: False
Test processed data matches saved file : False

Missing values:
Train: 0
Test : 0

Infinite values:
Train: 0
Test : 0

Verification completed.

In [28]:
# ==========================================
# Check Floating-Point Differences
# ==========================================

# Convert both DataFrames to numeric NumPy arrays
original_train_values = train_processed.to_numpy()
saved_train_values = train_processed_check.to_numpy()

original_test_values = test_processed.to_numpy()
saved_test_values = test_processed_check.to_numpy()

# Calculate the maximum absolute difference
train_max_diff = np.max(
    np.abs(original_train_values - saved_train_values)
)

test_max_diff = np.max(
    np.abs(original_test_values - saved_test_values)
)

print("Maximum absolute difference after CSV round-trip:\n")

print("Training data:", train_max_diff)
print("Testing data :", test_max_diff)

# Check whether the differences are within a very small tolerance
print("\nNumerically equivalent within tolerance:")

print(
    "Training:",
    np.allclose(
        original_train_values,
        saved_train_values,
        rtol=1e-9,
        atol=1e-12
    )
)

print(
    "Testing :",
    np.allclose(
        original_test_values,
        saved_test_values,
        rtol=1e-9,
        atol=1e-12
    )
)

Maximum absolute difference after CSV round-trip:

Training data: 7.105427357601002e-15
Testing data : 3.552713678800501e-15

Numerically equivalent within tolerance:
Training: True
Testing : True

In [29]:
# ==========================================
# Save Fitted Preprocessing Pipeline
# ==========================================

import joblib

# Create the artifacts directory
artifacts_path = project_path / "artifacts"
artifacts_path.mkdir(parents=True, exist_ok=True)

# Save the fitted preprocessor
preprocessor_path = artifacts_path / "preprocessor.pkl"

joblib.dump(preprocessor, preprocessor_path)

print("Fitted preprocessor saved successfully!\n")

print("File:", preprocessor_path)
print("Size:", round(preprocessor_path.stat().st_size / 1024, 2), "KB")

# Verify that the file exists
print("\nFile exists:", preprocessor_path.exists())

Fitted preprocessor saved successfully!

File: D:\TY_Sem1\MLOps\FairXAi\artifacts\preprocessor.pkl
Size: 4.09 KB

File exists: True

In [30]:
# ==========================================
# Verify Saved Preprocessor
# ==========================================

# Load the fitted preprocessor back from disk
preprocessor_check = joblib.load(preprocessor_path)

# Transform the same training and testing data
X_train_check = preprocessor_check.transform(X_train)
X_test_check = preprocessor_check.transform(X_test)

# Compare with the transformations produced earlier
train_preprocessing_match = np.allclose(
    X_train_processed,
    X_train_check,
    rtol=1e-9,
    atol=1e-12
)

test_preprocessing_match = np.allclose(
    X_test_processed,
    X_test_check,
    rtol=1e-9,
    atol=1e-12
)

print("Saved preprocessor verification:\n")

print("Training transformation matches:", train_preprocessing_match)
print("Testing transformation matches :", test_preprocessing_match)

print("\nOriginal processed shapes:")
print("X_train_processed:", X_train_processed.shape)
print("X_test_processed :", X_test_processed.shape)

print("\nReloaded transformation shapes:")
print("X_train_check:", X_train_check.shape)
print("X_test_check :", X_test_check.shape)

Saved preprocessor verification:

Training transformation matches: True
Testing transformation matches : True

Original processed shapes:
X_train_processed: (24000, 33)
X_test_processed : (6000, 33)

Reloaded transformation shapes:
X_train_check: (24000, 33)
X_test_check : (6000, 33)